/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mzj_ffmpegtest_FFmpegTest */

#ifndef _Included_com_mzj_ffmpegtest_FFmpegTest
#define _Included_com_mzj_ffmpegtest_FFmpegTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mzj_ffmpegtest_FFmpegTest
 * Method:    deCodeVideo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_mzj_ffmpegtest_FFmpegTest_deCodeVideo
  (JNIEnv *, jclass,jstring,jobject);


JNIEXPORT void JNICALL Java_com_mzj_ffmpegtest_FFmpegTest_deCodeAudio
        (JNIEnv *, jclass,jstring);


#ifdef __cplusplus
}
#endif
#endif
